-- liquibase formatted sql
-- changeset csidevops:20220811-003
ALTER TABLE CUSTOMER_MASTER_DATA 
ADD (POSTAL_CODE CHAR(10) );
-- rollback ALTER TABLE CUSTOMER_MASTER_DATA DROP COLUMN POSTAL_CODE;
-- rollback DELETE FROM CUSTOMER_MASTER_DATA WHERE POSTAL_CODE IS NOT NULL;
